name: Tests RAG

on:
  push:
    branches: [main,develop, feature/*]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupère le code
        uses: actions/checkout@v4

      - name: Installe Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installe uv
        uses: astral-sh/setup-uv@v4

      - name: Installe les dépendances
        run: uv sync

      - name: Lance les tests
        run: uv run pytest backend/tests/test_rag.py -v
        env:
          SECRET_KEY: test_secret_key_longue_32_chars_ok
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: "1440" 
          DATABASE_URL: postgresql://test:test@localhost/test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          GEMINI_API_KEY: test_key
          MODEL_PATH: app/models/f1_winner_model.joblib
          F1_PDF_PATH: data/rag/f1_regles.pdf
          CHROMA_DIR: data/rag/chroma_db
          COLLECTION_NAME: f1_knowledge
          CHUNK_SIZE: "500"
          CHUNK_OVERLAP: "80"
          EMBED_MODEL: all-MiniLM-L6-v2